//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo.SIANCentral
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    using System.Web.Script.Serialization;
    using Newtonsoft.Json;
    //[Serializable]
    public partial class CatCDI
    {
        public int Id_Cd { get; set; }
        public string Cd_Nombre { get; set; }
        public string Cd_DescCorta { get; set; }
        public Nullable<int> Cd_Tipo { get; set; }
        public string Cd_Region { get; set; }
    }
}
