//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo.CuentasCoorporativas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatCNac_ACYS
    {
        public CatCNac_ACYS()
        {
            this.CatAcys_Productos = new HashSet<CatAcys_Productos>();
            this.CatACYS_Productos_DatosGar = new HashSet<CatACYS_Productos_DatosGar>();
            this.CatACYS_Productos_DatosGar_Fechas = new HashSet<CatACYS_Productos_DatosGar_Fechas>();
            this.CatCNac_Estructura = new HashSet<CatCNac_Estructura>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Id_Matriz { get; set; }
        public string Nombre { get; set; }
        public string EjecCuenta { get; set; }
        public string LiderTecnico { get; set; }
        public Nullable<bool> DiasCredito { get; set; }
        public Nullable<bool> AcuerdoEcon { get; set; }
        public Nullable<bool> DatosFisc { get; set; }
        public Nullable<bool> AsigRIK { get; set; }
        public Nullable<bool> MOV80 { get; set; }
        public Nullable<int> NivelAcys { get; set; }
        public Nullable<int> TipoCuenta { get; set; }
        public Nullable<System.DateTime> FechaUltimaAct { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
    
        public virtual CatACYS_Cliente CatACYS_Cliente { get; set; }
        public virtual CatACYS_CondPago CatACYS_CondPago { get; set; }
        public virtual CatACYS_OtrosApoyos CatACYS_OtrosApoyos { get; set; }
        public virtual ICollection<CatAcys_Productos> CatAcys_Productos { get; set; }
        public virtual ICollection<CatACYS_Productos_DatosGar> CatACYS_Productos_DatosGar { get; set; }
        public virtual ICollection<CatACYS_Productos_DatosGar_Fechas> CatACYS_Productos_DatosGar_Fechas { get; set; }
        public virtual CatACYS_RecPedido CatACYS_RecPedido { get; set; }
        public virtual CatACYS_ServValor CatACYS_ServValor { get; set; }
        public virtual CatCNac_Matriz CatCNac_Matriz { get; set; }
        public virtual ICollection<CatCNac_Estructura> CatCNac_Estructura { get; set; }
    }
}
