//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo_CC.CuentasCoorporativas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapAcys_CNacServValor
    {
        public int Id_Emp { get; set; }
        public int Id_Cd { get; set; }
        public int Id_Acs { get; set; }
        public int Id_AcsVersion { get; set; }
        public Nullable<bool> ServAseRevLunes { get; set; }
        public Nullable<bool> ServAseRevMartes { get; set; }
        public Nullable<bool> ServAseRevMiercoles { get; set; }
        public Nullable<bool> ServAseRevJueves { get; set; }
        public Nullable<bool> ServAseRevViernes { get; set; }
        public Nullable<bool> ServAseRevSabado { get; set; }
        public string ServAseRevHora1Ini { get; set; }
        public string ServAseRevHora1Fin { get; set; }
        public string ServAseRevHora2Ini { get; set; }
        public string ServAseRevHora2Fin { get; set; }
        public string ServAsePersonaRecibe { get; set; }
        public string ServAsePuesto { get; set; }
        public Nullable<bool> ServAseCitaMismoDia { get; set; }
        public Nullable<bool> ServAseCitaSinCita { get; set; }
        public Nullable<bool> ServAseCitaPrevia { get; set; }
        public string ServAseCitaContacto { get; set; }
        public string ServAseCitaTelefono { get; set; }
        public Nullable<int> ServAseCitaDiasdeAnticipacion { get; set; }
        public Nullable<bool> ServAseAreaPropia { get; set; }
        public Nullable<bool> ServAseAreaPlaza { get; set; }
        public Nullable<bool> ServAseAreaCalle { get; set; }
        public Nullable<bool> ServAseEstCortesia { get; set; }
        public Nullable<bool> ServAseEstCosto { get; set; }
        public Nullable<double> ServAseEstMonto { get; set; }
        public Nullable<bool> ServAseAccesoClientes { get; set; }
        public Nullable<bool> ServAseAccesoProveedores { get; set; }
        public string ServAseDireccion { get; set; }
        public string ServAseColonia { get; set; }
        public string ServAseMunicipio { get; set; }
        public string ServAseEstado { get; set; }
        public string ServAseCP { get; set; }
        public string ServAseCiudad { get; set; }
        public Nullable<bool> ServTecRevLunes { get; set; }
        public Nullable<bool> ServTecRevMartes { get; set; }
        public Nullable<bool> ServTecRevMiercoles { get; set; }
        public Nullable<bool> ServTecRevJueves { get; set; }
        public Nullable<bool> ServTecRevViernes { get; set; }
        public Nullable<bool> ServTecRevSabado { get; set; }
        public string ServTecRevHora1Ini { get; set; }
        public string ServTecRevHora1Fin { get; set; }
        public string ServTecRevHora2Ini { get; set; }
        public string ServTecRevHora2Fin { get; set; }
        public string ServTecPersonaRecibe { get; set; }
        public string ServTecPuesto { get; set; }
        public Nullable<bool> ServTecCitaMismoDia { get; set; }
        public Nullable<bool> ServTecCitaSinCita { get; set; }
        public Nullable<bool> ServTecCitaPrevia { get; set; }
        public string ServTecCitaContacto { get; set; }
        public string ServTecCitaTelefono { get; set; }
        public Nullable<int> ServTecCitaDiasdeAnticipacion { get; set; }
        public Nullable<bool> ServTecAreaPropia { get; set; }
        public Nullable<bool> ServTecAreaPlaza { get; set; }
        public Nullable<bool> ServTecAreaCalle { get; set; }
        public Nullable<bool> ServTecEstCortesia { get; set; }
        public Nullable<bool> ServTecEstCosto { get; set; }
        public Nullable<double> ServTecEstMonto { get; set; }
        public Nullable<bool> ServTecAccesoClientes { get; set; }
        public Nullable<bool> ServTecAccesoProveedores { get; set; }
        public string ServTecDireccion { get; set; }
        public string ServTecColonia { get; set; }
        public string ServTecMunicipio { get; set; }
        public string ServTecEstado { get; set; }
        public string ServTecCP { get; set; }
        public string ServTecCiudad { get; set; }
        public Nullable<bool> ServAseDocFactFranquiciaEnt { get; set; }
        public Nullable<int> ServAseDocFactFranquiciaEntCop { get; set; }
        public Nullable<bool> ServAseDocFactFranquiciaRec { get; set; }
        public Nullable<int> ServAseDocFactFranquiciaRecCop { get; set; }
        public Nullable<bool> ServAseDocFactKeyEnt { get; set; }
        public Nullable<int> ServAseDocFactKeyEntCop { get; set; }
        public Nullable<bool> ServAseDocFactKeyRec { get; set; }
        public Nullable<int> ServAseDocFactKeyRecCop { get; set; }
        public Nullable<bool> ServAseDocOrdCompraEnt { get; set; }
        public Nullable<int> ServAseDocOrdCompraEntCop { get; set; }
        public Nullable<bool> ServAseDocOrdCompraRec { get; set; }
        public Nullable<int> ServAseDocOrdCompraRecCop { get; set; }
        public Nullable<bool> ServAseDocOrdReposEnt { get; set; }
        public Nullable<int> ServAseDocOrdReposEntCop { get; set; }
        public Nullable<bool> ServAseDocOrdReposRec { get; set; }
        public Nullable<int> ServAseDocOrdReposRecCop { get; set; }
        public Nullable<bool> ServAseDocCopPedidoEnt { get; set; }
        public Nullable<int> ServAseDocCopPedidoEntCop { get; set; }
        public Nullable<bool> ServAseDocCopPedidoRec { get; set; }
        public Nullable<int> ServAseDocCopPedidoRecCop { get; set; }
        public Nullable<bool> ServAseDocRemisionEnt { get; set; }
        public Nullable<int> ServAseDocRemisionEntCop { get; set; }
        public Nullable<bool> ServAseDocRemisionRec { get; set; }
        public Nullable<int> ServAseDocRemisionRecCop { get; set; }
        public Nullable<bool> ServAseDocFolioEnt { get; set; }
        public Nullable<int> ServAseDocFolioEntCop { get; set; }
        public Nullable<bool> ServAseDocFolioRec { get; set; }
        public Nullable<int> ServAseDocFolioRecCop { get; set; }
        public Nullable<bool> ServAseDocContraRecEnt { get; set; }
        public Nullable<int> ServAseDocContraRecEntCop { get; set; }
        public Nullable<bool> ServAseDocContraRecRec { get; set; }
        public Nullable<int> ServAseDocContraRecRecCop { get; set; }
        public Nullable<bool> ServAseDocEntAlmacenEnt { get; set; }
        public Nullable<int> ServAseDocEntAlmacenEntCop { get; set; }
        public Nullable<bool> ServAseDocEntAlmacenRec { get; set; }
        public Nullable<int> ServAseDocEntAlmacenRecCop { get; set; }
        public Nullable<bool> ServAseDocNomFirmaEnt { get; set; }
        public Nullable<int> ServAseDocNomFirmaEntCop { get; set; }
        public Nullable<bool> ServAseDocNomFirmaoRec { get; set; }
        public Nullable<int> ServAseDocNomFirmaRecCop { get; set; }
        public Nullable<bool> ServAseDocRecCitaEnt { get; set; }
        public Nullable<int> ServAseDocRecCitaEntCop { get; set; }
        public Nullable<bool> ServAseDocRecCitaRec { get; set; }
        public Nullable<int> ServAseDocRecCitaRecCop { get; set; }
        public Nullable<bool> ServAseDocSopServicioEnt { get; set; }
        public Nullable<int> ServAseDocSopServicioEntCop { get; set; }
        public Nullable<bool> ServAseDocSopServicioRec { get; set; }
        public Nullable<int> ServAseDocSopServicioRecCop { get; set; }
        public Nullable<bool> ServTecDocFactFranquiciaEnt { get; set; }
        public Nullable<int> ServTecDocFactFranquiciaEntCop { get; set; }
        public Nullable<bool> ServTecDocFactFranquiciaRec { get; set; }
        public Nullable<int> ServTecDocFactFranquiciaRecCop { get; set; }
        public Nullable<bool> ServTecDocFactKeyEnt { get; set; }
        public Nullable<int> ServTecDocFactKeyEntCop { get; set; }
        public Nullable<bool> ServTecDocFactKeyRec { get; set; }
        public Nullable<int> ServTecDocFactKeyRecCop { get; set; }
        public Nullable<bool> ServTecDocOrdCompraEnt { get; set; }
        public Nullable<int> ServTecDocOrdCompraEntCop { get; set; }
        public Nullable<bool> ServTecDocOrdCompraRec { get; set; }
        public Nullable<int> ServTecDocOrdCompraRecCop { get; set; }
        public Nullable<bool> ServTecDocOrdReposEnt { get; set; }
        public Nullable<int> ServTecDocOrdReposEntCop { get; set; }
        public Nullable<bool> ServTecDocOrdReposRec { get; set; }
        public Nullable<int> ServTecDocOrdReposRecCop { get; set; }
        public Nullable<bool> ServTecDocCopPedidoEnt { get; set; }
        public Nullable<int> ServTecDocCopPedidoEntCop { get; set; }
        public Nullable<bool> ServTecDocCopPedidoRec { get; set; }
        public Nullable<int> ServTecDocCopPedidoRecCop { get; set; }
        public Nullable<bool> ServTecDocRemisionEnt { get; set; }
        public Nullable<int> ServTecDocRemisionEntCop { get; set; }
        public Nullable<bool> ServTecDocRemisionRec { get; set; }
        public Nullable<int> ServTecDocRemisionRecCop { get; set; }
        public Nullable<bool> ServTecDocFolioEnt { get; set; }
        public Nullable<int> ServTecDocFolioEntCop { get; set; }
        public Nullable<bool> ServTecDocFolioRec { get; set; }
        public Nullable<int> ServTecDocFolioRecCop { get; set; }
        public Nullable<bool> ServTecDocContraRecEnt { get; set; }
        public Nullable<int> ServTecDocContraRecEntCop { get; set; }
        public Nullable<bool> ServTecDocContraRecRec { get; set; }
        public Nullable<int> ServTecDocContraRecRecCop { get; set; }
        public Nullable<bool> ServTecDocEntAlmacenEnt { get; set; }
        public Nullable<int> ServTecDocEntAlmacenEntCop { get; set; }
        public Nullable<bool> ServTecDocEntAlmacenRec { get; set; }
        public Nullable<int> ServTecDocEntAlmacenRecCop { get; set; }
        public Nullable<bool> ServTecDocNomFirmaEnt { get; set; }
        public Nullable<int> ServTecDocNomFirmaEntCop { get; set; }
        public Nullable<bool> ServTecDocNomFirmaoRec { get; set; }
        public Nullable<int> ServTecDocNomFirmaRecCop { get; set; }
        public Nullable<bool> ServTecDocRecCitaEnt { get; set; }
        public Nullable<int> ServTecDocRecCitaEntCop { get; set; }
        public Nullable<bool> ServTecDocRecCitaRec { get; set; }
        public Nullable<int> ServTecDocRecCitaRecCop { get; set; }
        public Nullable<bool> ServTecDocSopServicioEnt { get; set; }
        public Nullable<int> ServTecDocSopServicioEntCop { get; set; }
        public Nullable<bool> ServTecDocSopServicioRec { get; set; }
        public Nullable<int> ServTecDocSopServicioRecCop { get; set; }
    
        public virtual CapAcy CapAcys { get; set; }
    }
}
