//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo_CC.CuentasCoorporativas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapAcysDatosGarantia
    {
        public int Id_Emp { get; set; }
        public int Id_Acs { get; set; }
        public int Id_Cd { get; set; }
        public int Id_AcsVersion { get; set; }
        public int Id_TG { get; set; }
        public Nullable<double> FactorGarantia { get; set; }
        public Nullable<double> UPrimaNeta { get; set; }
        public Nullable<System.DateTime> FechaCorte { get; set; }
    }
}
