//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    using System.Web.Script.Serialization;
    using Newtonsoft.Json;
    //[Serializable]
    public partial class CapProyectoFaseBiblioNodo
    {
        public CapProyectoFaseBiblioNodo()
        {
            this.CapProyectoFaseEvidencias = new HashSet<CapProyectoFaseEvidencia>();
        }
    
        public int Id_Emp { get; set; }
        public int Id_Cd { get; set; }
        public int Id_U { get; set; }
        public int Id_Biblioteca { get; set; }
        public int Id_Op { get; set; }
        public int Id_Fase { get; set; }
        public int Id_BiblioNodo { get; set; }
    
    	[IgnoreDataMember]
    	[ScriptIgnore]
    	[JsonIgnore]
        public virtual CapProyectoBiblioNodo CapProyectoBiblioNodo { get; set; }
    	[IgnoreDataMember]
    	[ScriptIgnore]
    	[JsonIgnore]
        public virtual ICollection<CapProyectoFaseEvidencia> CapProyectoFaseEvidencias { get; set; }
    }
}
