//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    using System.Web.Script.Serialization;
    using Newtonsoft.Json;
    //[Serializable]
    public partial class CapValProyectoDet
    {
        public int Id_Emp { get; set; }
        public int Id_Cd { get; set; }
        public int Id_Vap { get; set; }
        public int Id_VapDet { get; set; }
        public int Vap_Tipo { get; set; }
        public int Id_Prd { get; set; }
        public int Vap_Cantidad { get; set; }
        public double Vap_Costo { get; set; }
        public double Vap_Precio { get; set; }
        public Nullable<System.DateTime> Det_FecAut { get; set; }
        public Nullable<int> Det_Autorizo { get; set; }
        public string Det_Estatus { get; set; }
        public Nullable<double> Det_PrecioLista { get; set; }
    }
}
