//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    using System.Web.Script.Serialization;
    using Newtonsoft.Json;
    //[Serializable]
    public partial class CatUsuario
    {
        public CatUsuario()
        {
            this.CapAcys = new HashSet<CapAcy>();
            this.CapAcys1 = new HashSet<CapAcy>();
            this.CapUsuarioNotificacions = new HashSet<CapUsuarioNotificacion>();
            this.CapBibliotecaUsuarios = new HashSet<CapBibliotecaUsuario>();
        }
    
        public int Id_Emp { get; set; }
        public int Id_Cd { get; set; }
        public int Id_U { get; set; }
        public string U_Nombre { get; set; }
        public string U_NombreCorto { get; set; }
        public string U_Correo { get; set; }
        public Nullable<System.DateTime> U_FNac { get; set; }
        public string U_NumNomina { get; set; }
        public Nullable<bool> U_Activo { get; set; }
        public Nullable<int> id_id_U { get; set; }
        public Nullable<int> Id_Tu { get; set; }
        public Nullable<bool> U_VerTodo { get; set; }
        public Nullable<bool> U_MultiOfi { get; set; }
        public Nullable<int> Id_Rik { get; set; }
        public Nullable<bool> U_SusCredito { get; set; }
        public Nullable<int> U_DiasVencimiento { get; set; }
        public Nullable<bool> U_AutorizaPrecio { get; set; }
        public string U_Telefono { get; set; }
        public Nullable<bool> U_ACYS { get; set; }
    
    	[IgnoreDataMember]
    	[ScriptIgnore]
    	[JsonIgnore]
        public virtual ICollection<CapAcy> CapAcys { get; set; }
    	[IgnoreDataMember]
    	[ScriptIgnore]
    	[JsonIgnore]
        public virtual ICollection<CapAcy> CapAcys1 { get; set; }
    	[IgnoreDataMember]
    	[ScriptIgnore]
    	[JsonIgnore]
        public virtual ICollection<CapUsuarioNotificacion> CapUsuarioNotificacions { get; set; }
    	[IgnoreDataMember]
    	[ScriptIgnore]
    	[JsonIgnore]
        public virtual ICollection<CapBibliotecaUsuario> CapBibliotecaUsuarios { get; set; }
    	[IgnoreDataMember]
    	[ScriptIgnore]
    	[JsonIgnore]
        public virtual CatCentroDistribucion CatCentroDistribucion { get; set; }
    }
}
