//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    using System.Web.Script.Serialization;
    using Newtonsoft.Json;
    //[Serializable]
    public partial class SysConfiguracion
    {
        public int Id_Emp { get; set; }
        public int Id_Cd { get; set; }
        public int Id_Conf { get; set; }
        public string Conf_Valor { get; set; }
        public string Conf_Descripcion { get; set; }
    }
}
